version: 2.1

# Define the jobs we want to run for this project
jobs:
  install:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - v1-yarn-deps-{{ checksum "yarn.lock" }}
            # Find the most recently generated cache used from any branch
            - v1-yarn-deps-
      - run:
          name: Install Dependencies test
          command: |
            yarn install
      - save_cache:
          key: v1-yarn-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - v1-yarn-deps-{{ checksum "yarn.lock" }}
            # Find the most recently generated cache used from any branch
            - v1-yarn-deps-
      - run:
          name: Build
          command: |
            yarn build
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - v1-yarn-deps-{{ checksum "yarn.lock" }}
            # Find the most recently generated cache used from any branch
            - v1-yarn-deps-
      - run:
          name: Test
          command: |
            yarn test --ci

# Orchestrate our job run sequence
workflows:
  install_and_test:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - install
